## Take the csv data files generated by psychopy experiments for the verb
## norming study (in "exp-scripts_psychopy/norming_1809/")
## and process them into a format that allows for easy coding.

# NB: Script is written to be sourced from the Rproject in the root directory
# of the project. All paths are relative to that root! (I.e., things will not
# work if script is called from the folder where it is actually located.)

getwd()  # should be "[whatever...]/2018_replication_sheb-pulv2013"


#  ------------------------------------------------------------------------
#  Define functions
#  ------------------------------------------------------------------------

# gets name of data files in "mypath" that contain "expname" in their name
get_data_filenames <- function(mypath = NULL, expname = NULL) {
  myfiles <- list.files(mypath)
  # match only csv files for the right experiment
  mymatch <- paste(".*", expname, ".*\\.csv", sep ="")
  myfiles <- myfiles[grep(mymatch, myfiles)]  
  # Exclude participant numbers in range 990-999 (used for testing only)
  myfiles <- myfiles[grep("^(?!99[0-9])", myfiles, perl = TRUE)]   
  myfiles
}
# example:
get_data_filenames("exp-scripts_psychopy/norming_1809/data", "verb_norming_L1")
get_data_filenames("exp-scripts_psychopy/norming_1809/data", "verb_norming_L2")
get_data_filenames("exp-scripts_psychopy/norming_1809/data", "lextale")



# reads CSV data files generated from "verb_norming_L1-swe_no_translation",
# processes them and saves them to disk to path_output.
verb_norming_L1swe <- function(filename, path_output) {
  df <- read.csv(filename, fileEncoding = "UTF-8")
  # extract participant number using regex
  pptID <- gsub(".*(\\d\\d\\d)_verb.*", "\\1", filename)
  # define the filename for output, including path to right folder
  out_filename_rating <- paste(path_output, pptID, "_verb_rating_L1swe.csv", sep = "")
  # relevant columns to keep for rating and translation, respectively
  cols_rat <- c('expName', 'date', 'participant', 'trials.thisN',
                'word', 'category', 'rating.response')
  # select the relevant rows and columns to keep for each of the data frames
  rat <- df[grepl("(Ben|Arm)", df$category), cols_rat]  # ratings
  # rename some of the columns
  names(rat)[4:7] <- c("trial", "verb", "rated_category", "rating")
  # write to disk
  write.csv(rat, out_filename_rating, row.names = FALSE, fileEncoding = "UTF-8")
}

# # Uncomment and run to see how function works
# verb_norming_L1swe("exp-scripts_psychopy/norming_1809/data/801_verb_norming_L1-swe_no_translation_2018_Sep_10_1155.csv",
#                    "norming_1809_analysis/data_coding/")


# similar to preceding but for "verb_norming_L2-eng_oral_translation"
# The output is saved as two different files, one for verb ratings, 
# the other for coding the translations they gave orally
verb_norming_L2eng <- function(filename, path_output) {
  df <- read.csv(filename, fileEncoding = "UTF-8")
  # extract participant number using regex
  pptID <- gsub(".*(\\d\\d\\d)_verb.*", "\\1", filename)
  # define the filename for output, including path to right folder
  out_filename_rating <- paste(path_output, pptID, "_verb_rating_L2eng.csv", sep = "")
  out_filename_transl <- paste(path_output, "TOCODE_", pptID,
                               "_L2-eng_oral_translation.csv", sep = "")
  # relevant columns to keep for rating and translation, respectively
  cols_rat <- c('expName', 'date', 'participant', 'trials.thisN',
                'word', 'category', 'rating.response')
  cols_tra <- c('expName', 'date', 'participant', 'trials.thisN', 'key_resp_7.rt',
                'word')
  # select the relevant rows and columns to keep for each of the data frames
  rat <- df[df$category %in% c("Arm", "Leg"), cols_rat]  # ratings
  tra <- df[df$key_resp_7.keys == "return", cols_tra]  # translations
  # rename some of the columns
  names(rat)[4:7] <- c("trial", "verb", "rated_category", "rating")
  names(tra)[4:6] <- c("trial", "resp_time", "verb")
  # add columns for coding
  tra$translation_simple <- ""
  tra$translation_details <- ""
  tra$comment <- ""
  # write to disk
  write.csv(rat, out_filename_rating, row.names = FALSE, fileEncoding = "UTF-8")
  write.csv(tra, out_filename_transl, row.names = FALSE, fileEncoding = "UTF-8")
}

# # Uncomment and run following line for running function with data from ppt 905
# verb_norming_L2eng("exp-scripts_psychopy/norming_1809/data/801_verb_norming_L2-eng_oral_translation_2018_Sep_10_1112.csv",
#                    "norming_1809_analysis/data_coding/")


#  ------------------------------------------------------------------------
#  Read, process and save to disk
#  ------------------------------------------------------------------------

# wrapper function to combine the above
process_raw_data <- function() {
  path_input <- "exp-scripts_psychopy/norming_1809/data/"
  path_output <- "norming_1809_analysis/data_coding/"
  
  # "verb_norming_L1-swe_no_translation" (NB: the expname
  # argument passed to the call below ensures that data files for psychopy exp
  # "verb_norming_oral_input" are excluded
  verbnorming_files_swe <- get_data_filenames(path_input, "verb_norming_L1-swe")
  for (myfile in verbnorming_files_swe) {
    verb_norming_L1swe(paste(path_input, myfile, sep=""), path_output)
  }
  
  # "verb_norming_L2-eng_oral_translation"
  verbnorming_files_eng <- get_data_filenames(path_input, "verb_norming_L2-eng")
  for (myfile in verbnorming_files_eng) {
    verb_norming_L2eng(paste(path_input, myfile, sep=""), path_output)
  }
  
}
# uncomment and run
process_raw_data()
