## Take the csv data files generated by psychopy experiments 
## "sheb_replic_pilot_control", "verb_norming", and "verb_norming_oral_input"
## and process them into a format that allows for easy coding.

# NB: Script is written to be sourced from the Rproject in the root directory
# of the project. All paths are relative to that root! (I.e., things will not
# work if script is called from the folder where it is actually located.)

getwd()  # should be "[whatever...]/2018_replication_sheb-pulv2013"

# function to process all raw data files and save into right folder
process_raw_data <- function(pptID = -9, saveToDisk = FALSE) {
  if (pptID == -9) {
    stop("No pptID provided. Set pptID = 'all' to preprocess data for all participants.")
  }
  path_input <- "exp-scripts_psychopy/pilot/data/"
  path_output <- "analysis/data_coding/"
  # First, pilot control experiment
  control_file <- paste(path_input, pptID, "_sheb_replic_pilot_control_2018_Jun_08_1031.csv", sep = "")
  control_exp <- read.csv(control_file, fileEncoding = "UTF-8")
  # relevant columns to keep
  keep_cols <- c('expName', 'date', 'participant', 'experimental_blocks.thisN',
            'word_duration', 'SOA', 'word_presentation.thisN',
            'type', 'key_resp_2.rt', paste('word', 1:4, sep = ""))
  # select the relevant rows and columns to keep
  control_exp <- control_exp[control_exp$type %in% c("arm", "leg"), keep_cols]
  # rename some of the columns
  names(control_exp)[c(4, 7, 9)] <- c("block", "trial", "trialRT")
  # add columns for coding
  newcols <- data.frame(w1 = "", w2 = "", w3 = "", w4 = "", error = "", score = "",
                        comment = "", coder = "")
  control_exp <- cbind(control_exp, newcols)
  if (saveToDisk) {
    write.csv(control_exp, 
              paste(path_output, "TOCODE_", pptID,
                    "_sheb_replic_pilot_control.csv", sep = ""),
              row.names = FALSE, fileEncoding = "UTF-8")
  } else control_exp
}
# # TO DO
# - Read all data files from an experiment in the folder
# - experiments: control, verb_norming, verb_norming_oral_input

process_raw_data(900, saveToDisk = TRUE)

p900 <- process_raw_data(900)
head(p900)
tail(p900)
names(p900)
