## Take the csv data files generated by psychopy experiments in our replication
## with natives (in "exp-scripts_psychopy/replication_pilot_1810/data/") and
## process them into a format that allows for easy coding.

library("dplyr")


#  ------------------------------------------------------------------------
#  Check folder structure and create paths to important directories
#  ------------------------------------------------------------------------

# NB: Script is written to be sourced from the Rproject in the root directory
# of the git project. All paths are relative to that root! (I.e., things will
# not work if script is called from the folder where it is actually located.)

getwd()  # should be "[whatever...]/2018_replication_sheb-pulv2013"

# path to the raw data files to be processed
input_folder <- "exp-scripts_psychopy/replication_pilot_1810/data"
if (! dir.exists(input_folder)) stop("Path to input folder doesn't exist!")

# Create output folder if it doesn't yet exist
output_folder <- "1810_replication-natives_analysis/data_coding"
if (! dir.exists(output_folder)) dir.create(output_folder)


#  ------------------------------------------------------------------------
#  Define functions
#  ------------------------------------------------------------------------

# gets name of data files in "mypath" that contain "expname" in their name
get_data_filenames <- function(mypath = NULL, expname = NULL) {
  myfiles <- list.files(mypath)
  # match only csv files for the right experiment
  mymatch <- paste(".*", expname, ".*\\.csv", sep ="")
  myfiles <- myfiles[grep(mymatch, myfiles)]  
  # Exclude participant numbers in range 990-999 (used for testing only)
  myfiles <- myfiles[grep("^(?!99[0-9])", myfiles, perl = TRUE)]
  myfiles
}
# example:
get_data_filenames(mypath = input_folder, "sheb_replication")
get_data_filenames(mypath = input_folder, "verb_norming")

#################################################

# reads CSV data files generated from "sheb_replication" experiment, processes 
# them and saves them to disk to path_output.
process_memory_task <- function(filename, path_output) {
  
  # load raw data file and process:
  df <- read.csv(filename, fileEncoding = "UTF-8") %>%
    # select relevant columns and rename for clarity
    select(expName, date, session, participant, block = block.thisN, 
           Movement = Effector, trial = word_presentation.thisN,
           type, trialRT = key_resp_2.rt, word1:word4) %>%
    # keep only relevant rows
    filter(type %in% c("arm", "leg"))
  
  # Rename type old-school way (select function couldn't [type isn't a good name!])
  names(df)[names(df) == "type"] <- "WordType"
  
  # Have Trial and Block start with 1 (instead of 0)
  df$trial <- df$trial + 1
  df$block <- df$block + 1

  # add columns for coding
  newcols <- data.frame(response = "", comment = "", coder = "")
  df <- cbind(df, newcols)
  
  # write to disk
  # define the filename for output, including path to right folder
  pptID <- unique(df$participant)  # participant ID number
  output_filename <- file.path(path_output, 
                               paste("TOCODE_", pptID, 
                                     "_sheb_replication.csv", sep = ""))
  print(output_filename)
  write.csv(df, output_filename, row.names = FALSE, fileEncoding = "UTF-8")
  df
}

# # Uncomment and run following line for running function with data from ppt 990
# x <- process_memory_task(
#   filename = file.path(input_folder, "990_sheb_replication_1810_2018_Sep_28_1240.csv"),
#   path_output = output_folder)

#################################################

# reads CSV data files generated from "verb_norming" experiment, processes them
# and saves them to disk to path_output. Output is saved as two different files,
# one for verb ratings, the other for multiple choice translation
verb_norming_L1eng <- function(filename, path_output) {
  
  # load raw data file and process:
  df <- read.csv(filename, fileEncoding = "UTF-8") %>%
    # select relevant columns and rename for clarity
    select(expName, date, participant, trial = trials.thisN, verb, 
           rated_category = category_lowercase, rating = rating.response) %>%
    # keep only relevant rows
    filter(rated_category %in% c("arm", "leg"))
  
  # Have Trial start with 1 (instead of 0)
  df$trial <- df$trial + 1

  # write to disk
  # define the filename for output, including path to right folder
  pptID <- unique(df$participant)  # participant ID number
  output_filename <- file.path(path_output, 
                               paste(pptID, "_verb_rating_L1eng.csv", sep = ""))
  print(output_filename)
  write.csv(df, output_filename, row.names = FALSE, fileEncoding = "UTF-8")
  df
  df
}


#  ------------------------------------------------------------------------
#  Read, process and save to disk
#  ------------------------------------------------------------------------

## Process and save the 2 pilot data files for technical checks

# OL's (?) data
process_memory_task(
  filename = file.path(input_folder, "990_sheb_replication_1810_2018_Sep_28_1240.csv"),
  path_output = output_folder)
verb_norming_L1eng(
  filename = file.path(input_folder, "990_verb_norming_L1-eng_no-translation_2018_Sep_28_1343.csv"),
  path_output = output_folder)

# GMM's data
process_memory_task(
  filename = file.path(input_folder, "991_sheb_replication_1810_2018_Oct_05_1305.csv"),
  path_output = output_folder)
verb_norming_L1eng(
  filename = file.path(input_folder, "991_verb_norming_L1-eng_no-translation_2018_Oct_05_1341.csv"),
  path_output = output_folder)


# wrapper function to combine the above for actual participants
process_raw_data <- function(
  path_input = input_folder,   # path to the raw data (CSV) files
  path_output = output_folder  # path where the processed data should be stored
  ) {
  
  # Memory task
  memory_files <- get_data_filenames(path_input, "sheb_replication")
  for (myfile in memory_files) {
    print(myfile)
    process_memory_task(filename = file.path(path_input, myfile),
                        path_output = file.path(path_output))
  }

  # Verb_norming task
  verbnorming_files <- get_data_filenames(path_input, "verb_norming")
  for (myfile in verbnorming_files) {
    print(myfile)
    verb_norming_L1eng(filename = file.path(path_input, myfile),
                       path_output = file.path(path_output))
  }

}
process_raw_data()
